---
title: "Blog Post - Simulation Study: CLT"
output: html_notebook
---

# The Central Limit Theorem

The central limit theorem is an important computational short-cut for
generating and making inference from the sampling distribution of the
mean. You’ll recall that the central limit theorem short-cut relies on a
number of conditions, specifically:

1.  Independent observations
2.  Identically distributed observations
3.  Mean and variance exist
4.  Sample size large enough for convergence

#Setup

In this simulation study, we are going to compare the sampling
distribution of the mean generated by simulation to the sampling
distribution implied by the central limit theorem. We will compare the
distributions graphically in QQ-plots.

This will be a 4 × 4 factorial experiment. The first factor will be the
sample size, with N = 5, 10, 20, and 40. The second factor will be the
degree of skewness in the underlying distribution. The underlying
distribution will be the Skew-Normal distribution. The Skew-Normal
distribution has three parameters: location, scale, and slant. When the
slant parameter is 0, the distribution reverts to the normal
distribution. As the slant parameter increases, the distribution becomes
increasingly skewed. In this simulation, slant will be set to 0, 2, 10,
100. Location and scale will be set to 0 and 1, respectively, for all simulation
settings.

To generate the simulated data, we will use the `rsn` function in the `sn` package.

The output of each combination of factors will be a QQ-plot. In this study, we will generate a
sampling distribution of 5000 draws from both the CLT approximation and
the simulation approximation. When analyzing data, the parameters for
the mean and variance (in the case of the CLT shortcut) or the
parameters for the distribution (in the case of MLE, MM, etc) are
replaced with sample estimates. (This is often called the plug-in
approach.) For the purposes of this simulation, we treat the mean and
variance as known values and use the actual population parameters and
the population mean and variance instead of sample estimates.


```{r}
require(magrittr)
library(sn)
# Parameters that do not change
parameters <- list(N = 5, slant = 10, R = 5000, location = 0, scale = 1)

generate_data <- function(parameter) {
    parameter$dist <- rsn(n = parameter$N, alpha = parameter$slant)
    
}

generate_samp_dist <- function(parameter)
sample_dist_sim <- rep(NA, R)
for (i in 1:5000) {
    sample_dist_sim[i] <- generate_data(N,slant) %>% mean(na.rm=TRUE)
}

# Quantites to calculate/generate
sigma <- slant/sqrt(1+ (slant^2))
pop_mean <- sqrt(2/3.14)*sigma
pop_variance <- (1-(2*(sigma^2)/3.14))
sample_dist_clt <- rnorm(5000, pop_mean, sqrt(pop_variance/N))


# QQ plot
qqplot(sample_dist_sim, sample_dist_clt, asp = 1)
abline(0,1)


prop.test(c(30,35), c(100,100))
```


Advanced (optional)
-------------------

Overlay in each figure the QQ-plot that results when the mean and
variance parameters are estimated from data, instead of using the
population parameters.
